package D0225009;
public class SaldiJhy {
    public static void main(String[] args) {
    String nama,aku;
    nama = " Rizaldi";
    aku = "Saldi";
    int umur,no;
    umur = 18;
    no = 7;
    long nomor = 100;
    long monor = 200;
    byte angka = 10;
    byte angka1 = 20;
    short angka2 = 30;
    short angka3 = 40;
    double des = 1.5;
    double des1 = 2.5;
    float DES1 = 10.4f;
    float DES2 =20.5f;
    char kelas = 'A';
    char goldar = 'O';
    boolean laki = true;
    boolean perempuan = false;
       System.out.println("Sebelum  update");
        System.out.printf("%s",nama);
        System.out.printf("\n%s",aku);
        System.out.printf("\n%d",umur);
        System.out.printf("\n%d",no);
        System.out.print("\n"+nomor);
        System.out.print("\n"+monor);
        System.out.print("\n"+angka);
        System.out.print("\n"+angka2);
        System.out.print("\n"+angka3);
        System.out.print("\n"+des);
        System.out.println("\n"+des1);
        System.out.println(DES1);
        System.out.println(DES2);
        System.out.println(kelas);
        System.out.println(goldar);
        System.out.println(laki);
        System.out.println(perempuan);
        System.out.println("" );
    
   nama = "ZALDI";
   aku = "RIZAL";
   umur = 19;
   no = 9;
   nomor = 1000;
   monor = 500;
   angka = 40;
   angka1 = 90;
   angka2 = 50;
   angka3 = 900;
   des = 10.5;
   des1 = 20.5;
   DES1 = 700.0f;
   DES2 = 5000.0f;
   kelas = 'B';
   goldar = 'A';
   laki = false;
   perempuan = true;
      System.out.println("Sebelum  update");
        System.out.printf("%s",nama);
        System.out.printf("\n%s",aku);
        System.out.printf("\n%d",umur);
        System.out.printf("\n%d",no);
        System.out.print("\n"+nomor);
        System.out.print("\n"+monor);
        System.out.print("\n"+angka);
        System.out.print("\n"+angka2);
        System.out.print("\n"+angka3);
        System.out.print("\n"+des);
        System.out.println("\n"+des1);
        System.out.println(DES1);
        System.out.println(DES2);
        System.out.println(kelas);
        System.out.println(goldar);
        System.out.println(laki);
        System.out.println(perempuan);
        System.out.println("" );
    
    }
}
